### ISSUE TITLE
AddToCart DataLayer Price is 0, when shopping cart isn't empty.

### ISSUE THREAD

**Issue by T3rmiXx** [webmatch/WbmTagManagerEcomm#13]
When i add a product to the shopping cart, the addToCart DataLayer correctly fills in the price.
![first](https://user-images.githubusercontent.com/40434446/95308520-4faa4500-088a-11eb-911f-7aef10da369c.png)

But when i add a different product, the price for the new product in the DataLayer is set to 0.
![second](https://user-images.githubusercontent.com/40434446/95308557-5afd7080-088a-11eb-9ed6-bf23c4782aac.png)

I tested this in different Shops (local and online) and with the newest Version but this bug appears every time.

**Comment by benjamin-ott** [comment]
I had the same issue and i think it occurs in the cartaddprice twig function here:
https://github.com/webmatch/WbmTagManagerEcomm/blob/master/src/Twig/TagManagerExtension.php#L161

A lineItem is defined in line 172 and the foreach overrides it in line 189

**Comment by wbm-sbasler** [comment]
fixed, see PR above
