### ISSUE TITLE
Rendering will break with 500 error on multi language

### ISSUE THREAD

**Issue by Isengo1989** [webmatch/WbmTagManagerEcomm#14]
$salesChannelContext->getSalesChannel()->getName() on a french shop leads to a 500 error since $this->cartService->createNew expects the second param to be a string and not Null.

Since it is only a temp basket I would leave this empty and use the default "sales-channel"

https://github.com/webmatch/WbmTagManagerEcomm/blob/ea2fc2c5f8330d6302179b779fffe24bfdd42949/src/Twig/TagManagerExtension.php#L184

**Comment by wbm-sbasler** [comment]
fixed, see PR above
