### ISSUE TITLE
Iframe ad 404 error

### ISSUE THREAD

**Issue by runelaenen** [webmatch/WbmTagManagerEcomm#18]
**Description:** 
The iframe loaded in `wbm-tagmanager-tabs` gives an error because the page does not exist.

https://plugins.webmatch.de/wbm_tag_manager/info.php gives a 404.

**Expected result:** 
Advertisment

**Current result:** 
Error

**Possible solution:**
Remove ad

**Comment by wbm-sbasler** [comment]
Thanks four your hint, there was a DNS misconfiguration.
