### ISSUE TITLE
'wbm-tagmanager-enabled' cookie is not set

### ISSUE THREAD

**Issue by Konstantin-Sharohin** [webmatch/WbmTagManagerEcomm#25]
Hello, everyone!

I would like to ask, if the 'wbm-tagmanager-enabled' cookie should be set automatically or manually? The reason I'm asking, because I try to setup a custom tag using the GTM and cannot make it fire in a preview mode.
So the `gtmCookieSet` variable is never set during the run of the GTM initialization script in the 'head' tag...

Moreover (see the latest screenshot below), the container that I'm trying to test (GTM-WFLDW6F) is not loaded, but instead loads some other container (UA-22397531), that is generally never existed (I suppose it gets autogenerated for some reason). And the GTM-WFLDW6F container gets loaded and showed in Summary screen only after the manual run of the `googleTag` function...

**Shopware version:** 6

![Screen Shot 2020-12-08 at 13 01 50](https://user-images.githubusercontent.com/45078528/101482854-faf57a00-395f-11eb-8972-d61f399ae329.png)

![Screen Shot 2020-12-08 at 14 38 31](https://user-images.githubusercontent.com/45078528/101485176-74429c00-3963-11eb-9a4f-25dc3e5c2247.png)

**Comment by wbm-sbasler** [comment]
First of all, can you please stick to the ["reporting a bug"-template](https://github.com/webmatch/WbmTagManagerEcomm/issues/16)?

The `wbm-tagmanager-enabled` cookie will be set by the shopware integrated consent manager when the user agrees to `Google Tag Manager`. If you do not use that integrated consent manager you have to disable it in the configuration: `Shopware Cookie consent support`.

And I have no idea where `UA-22397531` came from, I'm quite sure that it is not from our plugin. I seems as if you additionally included google analytics code.

**Comment by Konstantin-Sharohin** [comment]
Thanks for the reply. I did't use "reporting a bug"-template, because I believe it's not a bug and I just wanted to ask how this cookie could be set (so I also added some relevant info).

So the user has to manually agree to use GTM in a Shopware, otherwise this `wbm-tagmanager-enabled` cookie will be unset?

**Comment by wbm-sbasler** [comment]
That is correct. When the shopware consent manager is used, the user has to agree to "google tag manager", otherwise the `wbm-tagmanager-enabled` cookie won't be set. But you can disable that behaviour in the configuration: `Shopware Cookie consent support`.

**Comment by Konstantin-Sharohin** [comment]
I got it. That will help in my findings a lot.

Thank you for your time.

**Comment by wbm-sbasler** [comment]
I close this issue for now, if you have any question about this feel free to reopen it.
