### ISSUE TITLE
Support of debug + preview mode

### ISSUE THREAD

**Issue by dmfilipenko** [webmatch/WbmTagManagerEcomm#26]
Google tag manager support debug + preview mode, but seems like this plugin rewrite all query params on a script.
It append `https://www.googletagmanager.com/gtm.js?id=GTM-CONTAINER` but we are expecting to append this 
`https://www.googletagmanager.com/gtm.js?id=GTM-CONTAINER&gtm_debug=x&gtm_auth=token&gtm_preview=env-4`

**Comment by wbm-sbasler** [comment]
First of all, can you please stick to the ["reporting a bug"-template](https://github.com/webmatch/WbmTagManagerEcomm/issues/16)?

But did you try the "Extended URL parameter (optional/expert)" configuration option?
>Add your extending GTM-URL parameter for test/stage environments here. These will be added to the googetagmanger.com URL. e.g.
&amp;gtm_auth=sOmeR4nd0mh45h&amp;gtm_preview=env-69&amp;gtm_cookies_win=x

**Comment by wbm-sbasler** [comment]
@dmfilipenko I assume this issue is resolved, so I close it.
