### ISSUE TITLE
Not visible on packagist?

### ISSUE THREAD

**Issue by zolthan** [webmatch/WbmTagManagerEcomm#3]
Hi Webmatch,
currently your plugin is not visible at packagist. Do you know why?
https://packagist.org/packages/webmatch/
We'd like to include the newest version via composer and it is not found yet.

Best Sebastian

**Comment by zolthan** [comment]
Hey @wbm-sbasler 
it is rather urgent. We need the TagManager working in 6.2.2. Could you force the plugin being listed in packagist?
Best Sebastian

**Comment by wbm-sbasler** [comment]
Hi @zolthan 
we are planing to publish the package as soon as possible on packagist.
Greetings Sebastian

**Comment by wbm-sbasler** [comment]
Hi @zolthan 
the package has just become available at packagist.
Have fun with it.
Greetings Sebastian
