### ISSUE TITLE
Performance issue: Plugin creates very large carts

### ISSUE THREAD

**Issue by pottink** [webmatch/WbmTagManagerEcomm#34]
This plugin creates very large carts. After running this plugin in over less than a month it keeps adding temporaryToken carts with a very large number of line items. This causes the cart table to fill up. In our project we currently see the cart table getting ~45GB big and growing every day on a large product database. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/2572887/104033807-540b3480-51d0-11eb-8a3b-4af96c3c71f4.png)

It is caused by the cartaddprice method in the TagManagerExtension.php. This twig function is called every time there is a 'frontend.checkout.line-item.add' action.

**Comment by BrentRobert** [comment]
The whole 'cartaddprice' method should be rewritten, cause the way this is calculated right now is just plain wrong.
Executing cart logic from a twig template?

**Comment by wbm-sbasler** [comment]
It is planned to complete refactor this function (and on which event it will be called) around may/june. As this is a free plugin we can not give a higher prio for that. But if you already have a solution, it would be nice to see it in a pull request

**Comment by andreasemer** [comment]
Currently this extension is unusable because of this issue.

**Comment by PheysX** [comment]
Is it possible to remove it after the temporary cartaddprice calculation? I dont see a reason why it dont should be removed after.
