### ISSUE TITLE
Installation recommendation as composer dependency

### ISSUE THREAD

**Issue by patpilus** [webmatch/WbmTagManagerEcomm#5]
Hey!

Is there any reason why it's suggested in [README](https://github.com/webmatch/WbmTagManagerEcomm#installation) to clone the plugin source code into `custom/plugins` in repository? 

As the plugin is published on packagist, it's possible to install it as a composer dependency:
```
composer require webmatch/tag-manager-sw6
```

Shopware 6 can handle and it can be easily installed/updated via console commands:
```
bin/console plugin:refresh
bin/console plugin:update WbmTagManagerEcomm 
```

**Comment by wbm-sbasler** [comment]
Thanks for your hint. Just didn't update the readme when publishing it on packagist, sry for that.
Will be fixed in the next release
