### ISSUE TITLE
Compatibility met ACRIS EU Cookie Policy Pro

### ISSUE THREAD

**Issue by shopworksnl** [webmatch/WbmTagManagerEcomm#7]
Hi,

1st of all, we love your tag manager plugin!
2nd, we are running into compatibility issues with ACRIS EU Cookie Policy Pro v 2.5.0 (since we are on SW6.2.3 with this specific customer) and your 1.0.0 version. Although we set the cookie as functional cookie it is not being loaded.
Do you have a suggestion perhaps?

**Comment by wbm-sbasler** [comment]
Currently we do not support other consent managers than the shopware consent manager, for now the wbm-tag-manager cookie has to be set by SW consent manager. We are working on it and plan to release a new version within the next 2 weeks, in that release you can choose not to use the SW consent manager.

**Comment by janssentwh** [comment]
Hi wbm-sbaslar,

Is there any news regarding this functionality? Mainly about its intended release date.

**Comment by wbm-sbasler** [comment]
@janssentwh Please have a look at our new release:
https://store.shopware.com/wbm1713539203085f/google-tag-manager-google-analytics-enhanced-e-commerce-tracking-fuer-shopware-6.html

**Comment by shopworksnl** [comment]
cool, thanks guys!
