### ISSUE TITLE
Matomo Tag Manager

### ISSUE THREAD

**Issue by csaeum** [webmatch/WbmTagManagerEcomm#70]
### Please describe the feature you would like to see implemented.

Ich würde es gut finden, wenn ihr es auch ermöglicht das man den Matomo Tag Manager nutzen kann.

So das man zb beide nutzen kann oder nur einen.

Zwecks Datenschutz nutze ich lieber den Matomo Tag Manager und wenn der Besucher alle Cookies akzeptiert dann spielt der Matomo Tag Manager die Daten auch zu Google. Wenn der Besucher es nicht zulässt dann gehen die Daten nur ins Matomo.

**Comment by wbm-sbasler** [comment]
Currently we only support google tag manager and it is not planned to support other tag manager services as well. Maybe the changes in #71 helps.
