### ISSUE TITLE
WbmTagManagerEcomm dont supports multiple sales channels

### ISSUE THREAD

**Issue by alexSanni** [webmatch/WbmTagManagerEcomm#8]
Die gesonderten Einstellungen der Verkaufgskanäle werden nicht beachtet. Er bezieht die GTM Container ID immer aus den Globalen Plugin Einstellungen.

**Comment by alexSanni** [comment]
[Hier](https://github.com/webmatch/WbmTagManagerEcomm/compare/master...alexSanni:master) habe ich einen Hotfix gebaut. Ist für meine Situation erstmal okay, weiter komme ich nicht mit meiner Symfony Erfahrung.

**Comment by wbm-sbasler** [comment]
We have an open pull request for this issue: https://github.com/webmatch/WbmTagManagerEcomm/pull/9
Once taht is merged, this issue will be fixed.

ps. we recommend to speak english here, as this is an international project
